//! Core execution loop for the Security Compass Interpreter.
//!
//! This module implements `Interpreter::new()`, `execute()`, and `continue_execution()`.
//! The execution loop intercepts VM function calls, evaluates SQRT policies, and
//! yields to the caller for tool execution or QLLM routing.

use std::collections::{HashMap, HashSet};
use std::sync::Arc;

use security_compass_meta::{Metadata, ValueWithMeta};
use security_compass_vm::{
    CollectStringPrint, ExcType, ExternalResult, LimitedTracker, MontyException,
    MontyObject, MontyRun, ResourceLimits, RunProgress,
};
use sqrt_eval::{CompiledPolicy, PolicyDecision};

use crate::branch_checker::PolicyBranchChecker;
use crate::convert::monty_to_json;
use crate::error::InterpreterError;
use crate::policy::{
    PARSE_WITH_AI, PARSE_WITH_AI_PARAMS, VERIFY_HYPOTHESIS, VERIFY_HYPOTHESIS_PARAMS,
    apply_session_updates, build_tool_call_context, positional_to_named,
};
use crate::types::{
    ExecutionResult, Interpreter, InterpreterConfig, ToolCallOutcome, ToolCallRecord,
    ToolDefinition, VmSnapshot,
};

impl Interpreter {
    /// Creates a new interpreter with the given compiled policy and configuration.
    ///
    /// The policy is wrapped in `Arc` so it can be shared with `PolicyBranchChecker`
    /// instances without cloning.
    pub fn new(policy: CompiledPolicy, config: InterpreterConfig) -> Self {
        let gas_remaining = if config.gas_limit > 0 {
            config.gas_limit
        } else {
            u64::MAX
        };

        Self {
            policy: Arc::new(policy),
            session_meta: Metadata::default(),
            config,
            tool_call_history: Vec::new(),
            gas_remaining,
            tool_call_count: 0,
            tool_cache: HashMap::new(),
            tool_arg_names: HashMap::new(),
            print_output: String::new(),
            deterministic_tools: HashSet::new(),
        }
    }

    /// Creates a new interpreter with a pre-constructed `Arc<CompiledPolicy>`.
    ///
    /// Use this when you need to share the policy with other components.
    pub fn new_with_arc(policy: Arc<CompiledPolicy>, config: InterpreterConfig) -> Self {
        let gas_remaining = if config.gas_limit > 0 {
            config.gas_limit
        } else {
            u64::MAX
        };

        Self {
            policy,
            session_meta: Metadata::default(),
            config,
            tool_call_history: Vec::new(),
            gas_remaining,
            tool_call_count: 0,
            tool_cache: HashMap::new(),
            tool_arg_names: HashMap::new(),
            print_output: String::new(),
            deterministic_tools: HashSet::new(),
        }
    }

    /// Executes a PLLM-generated Python program with metadata tracking and policy enforcement.
    ///
    /// This is the main entry point for running code through the interpreter.
    ///
    /// # Arguments
    /// * `python_code` - The Python code to execute (generated by the PLLM)
    /// * `input_vars` - Named input variables with their values and metadata
    /// * `tool_definitions` - External tools available to the program
    ///
    /// # Returns
    /// An `ExecutionResult` that is either `Complete` or a yield point requiring
    /// external work (tool call, parse_with_ai, verify_hypothesis).
    ///
    /// # Errors
    /// Returns `InterpreterError` for VM errors, policy errors, or limit violations.
    pub fn execute(
        &mut self,
        python_code: &str,
        input_vars: Vec<(String, ValueWithMeta<serde_json::Value>)>,
        tool_definitions: &[ToolDefinition],
    ) -> Result<ExecutionResult, InterpreterError> {
        // 1. Reset per-execution state
        self.tool_call_count = 0;
        self.gas_remaining = if self.config.gas_limit > 0 {
            self.config.gas_limit
        } else {
            u64::MAX
        };
        self.tool_call_history.clear();
        self.tool_cache.clear();
        self.print_output.clear();

        // 2. Build tool_arg_names map from tool definitions + internal tools
        self.tool_arg_names.clear();
        self.deterministic_tools.clear();
        for tool in tool_definitions {
            self.tool_arg_names
                .insert(tool.name.clone(), tool.parameter_names.clone());
            if tool.deterministic {
                self.deterministic_tools.insert(tool.name.clone());
            }
        }
        // Internal tools
        self.tool_arg_names.insert(
            PARSE_WITH_AI.to_string(),
            PARSE_WITH_AI_PARAMS.iter().map(|s| (*s).to_string()).collect(),
        );
        self.tool_arg_names.insert(
            VERIFY_HYPOTHESIS.to_string(),
            VERIFY_HYPOTHESIS_PARAMS.iter().map(|s| (*s).to_string()).collect(),
        );

        // 3. Separate input_vars into (names, values, metas)
        let mut input_names: Vec<String> = Vec::with_capacity(input_vars.len());
        let mut input_values: Vec<MontyObject> = Vec::with_capacity(input_vars.len());
        let mut input_metas: Vec<Metadata> = Vec::with_capacity(input_vars.len());

        for (name, vwm) in input_vars {
            input_names.push(name);
            input_values.push(crate::convert::json_to_monty(vwm.value));
            input_metas.push(vwm.meta);
        }

        // 4. Build external_functions list = tool names + internal tools
        let mut external_functions: Vec<String> = tool_definitions
            .iter()
            .map(|t| t.name.clone())
            .collect();
        external_functions.push(PARSE_WITH_AI.to_string());
        external_functions.push(VERIFY_HYPOTHESIS.to_string());

        // 5. Create MontyRun
        let vm = MontyRun::new(
            python_code.to_owned(),
            "pllm_program.py",
            input_names,
            external_functions,
        )?;

        // 6. Build resource tracker
        let resource_limits = ResourceLimits::new();
        let tracker = LimitedTracker::new(resource_limits);

        // 7. Create branch checker
        let branch_checker = PolicyBranchChecker::new(Arc::clone(&self.policy));

        // 8. Start execution with metadata and branch checker
        let mut print_writer = CollectStringPrint::new();
        let progress = vm.start_with_meta(
            input_values,
            input_metas,
            tracker,
            &mut print_writer,
            Some(Box::new(branch_checker)),
        )?;

        // Capture any print output from start phase
        self.print_output.push_str(print_writer.output());

        // 9. Enter the execution loop
        self.continue_execution(progress)
    }

    /// The main execution loop: processes `RunProgress` yield points.
    ///
    /// This method loops on the VM's yield points, handling:
    /// - **FunctionCall**: Policy evaluation, caching, internal tool routing
    /// - **OsCall**: Denied (not allowed in the interpreter)
    /// - **ResolveFutures**: Not supported (async)
    /// - **Complete**: Return the final result
    pub(crate) fn continue_execution(
        &mut self,
        mut progress: RunProgress<LimitedTracker>,
    ) -> Result<ExecutionResult, InterpreterError> {
        loop {
            match progress {
                RunProgress::FunctionCall {
                    function_name,
                    args,
                    kwargs: _,
                    args_meta,
                    call_id,
                    state,
                } => {
                    // Handle the function call — may yield, loop, or error
                    match self.handle_function_call(
                        &function_name,
                        &args,
                        &args_meta,
                        call_id,
                        state,
                    )? {
                        FunctionCallAction::Yield(result) => return Ok(result),
                        FunctionCallAction::Resume(new_progress) => {
                            progress = new_progress;
                        }
                    }
                }

                RunProgress::OsCall { function, .. } => {
                    return Err(InterpreterError::OsCallDenied {
                        function: format!("{function}"),
                    });
                }

                RunProgress::ResolveFutures(_) => {
                    return Err(InterpreterError::AsyncNotSupported);
                }

                RunProgress::Complete(obj, meta) => {
                    let value = monty_to_json(&obj)?;
                    return Ok(ExecutionResult::Complete {
                        value,
                        meta,
                        print_output: std::mem::take(&mut self.print_output),
                    });
                }
            }
        }
    }

    /// Handles a single function call from the VM.
    ///
    /// Returns either a yield point (the caller must provide the tool result)
    /// or a new `RunProgress` to continue the loop with (tool was denied/cached/internal).
    fn handle_function_call(
        &mut self,
        function_name: &str,
        args: &[MontyObject],
        args_meta: &[Metadata],
        call_id: u32,
        state: VmSnapshot,
    ) -> Result<FunctionCallAction, InterpreterError> {
        // 1. Check gas and tool call limits
        self.check_limits()?;

        // 2. Decrement gas
        if self.config.gas_limit > 0 {
            self.gas_remaining = self.gas_remaining.saturating_sub(1);
        }
        self.tool_call_count += 1;

        // 3. Get parameter names for this tool
        let param_names = self
            .tool_arg_names
            .get(function_name)
            .ok_or_else(|| InterpreterError::UnknownTool {
                name: function_name.to_string(),
            })?
            .clone();

        // 4. Convert positional args to named args
        let named_args = positional_to_named(args, args_meta, &param_names)?;

        // 5. Handle internal tools (parse_with_ai, verify_hypothesis)
        if function_name == PARSE_WITH_AI {
            return self.handle_parse_with_ai(named_args, call_id, state);
        }
        if function_name == VERIFY_HYPOTHESIS {
            return self.handle_verify_hypothesis(named_args, call_id, state);
        }

        // 6. Check LLM blocked tag if enabled
        if self.policy.preset.enable_llm_blocked_tag {
            let any_blocked = named_args.values().any(|vwm| vwm.meta.is_llm_blocked());
            if any_blocked {
                // Resume VM with RuntimeError exception
                let exc = MontyException::new(
                    ExcType::RuntimeError,
                    Some(format!(
                        "Tool call to '{function_name}' blocked: arguments carry __llm_blocked tag"
                    )),
                );
                self.tool_call_history.push(ToolCallRecord {
                    tool_name: function_name.to_string(),
                    call_id,
                    outcome: ToolCallOutcome::Denied {
                        reason: "LLM blocked tag on arguments".to_string(),
                    },
                });
                let new_progress = self.resume_vm_with_exception(state, exc)?;
                return Ok(FunctionCallAction::Resume(new_progress));
            }
        }

        // 7. Check tool cache
        let cache_key = Self::cache_key(function_name, &named_args);
        if let Some(cached) = self.tool_cache.get(&cache_key) {
            // Cache hit — resume VM with cached result
            let result_obj = crate::convert::json_to_monty(cached.value.clone());
            let result_meta = cached.meta.clone();
            self.tool_call_history.push(ToolCallRecord {
                tool_name: function_name.to_string(),
                call_id,
                outcome: ToolCallOutcome::Cached,
            });
            let new_progress = self.resume_vm_with_result(state, result_obj, result_meta)?;
            return Ok(FunctionCallAction::Resume(new_progress));
        }

        // 8. Evaluate SQRT policy
        let ctx = build_tool_call_context(function_name, &named_args, &self.session_meta);
        let decision =
            sqrt_eval::evaluate(&self.policy, &ctx, self.config.fail_fast)?;

        match decision {
            PolicyDecision::Allow {
                result_updates,
                session_before_updates,
                session_after_updates,
            } => {
                // Apply session_before_updates immediately
                apply_session_updates(&mut self.session_meta, &session_before_updates);

                // Yield to caller: tool call needs execution
                Ok(FunctionCallAction::Yield(ExecutionResult::NeedsToolCall {
                    tool_name: function_name.to_string(),
                    args: named_args,
                    call_id,
                    state,
                    result_updates,
                    session_after_updates,
                }))
            }

            PolicyDecision::Deny {
                reason,
                enforcement: _,
                rule_description,
            } => {
                // Tool call denied by policy — resume VM with exception
                let deny_message = if let Some(desc) = &rule_description {
                    format!("Tool call to '{function_name}' denied: {reason} ({desc})")
                } else {
                    format!("Tool call to '{function_name}' denied: {reason}")
                };
                let exc = MontyException::new(ExcType::RuntimeError, Some(deny_message.clone()));
                self.tool_call_history.push(ToolCallRecord {
                    tool_name: function_name.to_string(),
                    call_id,
                    outcome: ToolCallOutcome::Denied { reason: deny_message },
                });
                let new_progress = self.resume_vm_with_exception(state, exc)?;
                Ok(FunctionCallAction::Resume(new_progress))
            }
        }
    }

    /// Handles the `parse_with_ai` internal tool call.
    ///
    /// Extracts the `data`, `query`, and `output_schema` arguments and yields
    /// `NeedsParseWithAi` to the caller.
    fn handle_parse_with_ai(
        &mut self,
        named_args: indexmap::IndexMap<String, ValueWithMeta<serde_json::Value>>,
        call_id: u32,
        state: VmSnapshot,
    ) -> Result<FunctionCallAction, InterpreterError> {
        // Check LLM blocked tag on args
        if self.policy.preset.enable_llm_blocked_tag {
            let any_blocked = named_args.values().any(|vwm| vwm.meta.is_llm_blocked());
            if any_blocked {
                return Err(InterpreterError::LlmBlocked {
                    tool_name: PARSE_WITH_AI.to_string(),
                });
            }
        }

        // Extract arguments by position (data, query, output_schema)
        let data = named_args
            .get("data")
            .cloned()
            .unwrap_or_else(|| ValueWithMeta {
                value: serde_json::Value::Null,
                meta: Metadata::default(),
            });

        let query = named_args
            .get("query")
            .and_then(|v| v.value.as_str())
            .unwrap_or("")
            .to_string();

        let output_schema = named_args
            .get("output_schema")
            .map(|v| v.value.clone())
            .unwrap_or(serde_json::Value::Null);

        Ok(FunctionCallAction::Yield(
            ExecutionResult::NeedsParseWithAi {
                data,
                query,
                output_schema,
                call_id,
                state,
            },
        ))
    }

    /// Handles the `verify_hypothesis` internal tool call.
    ///
    /// Extracts the `hypothesis` and `data` arguments and yields
    /// `NeedsVerifyHypothesis` to the caller.
    fn handle_verify_hypothesis(
        &mut self,
        named_args: indexmap::IndexMap<String, ValueWithMeta<serde_json::Value>>,
        call_id: u32,
        state: VmSnapshot,
    ) -> Result<FunctionCallAction, InterpreterError> {
        // Check LLM blocked tag on data arg
        if self.policy.preset.enable_llm_blocked_tag {
            if let Some(data_arg) = named_args.get("data") {
                if data_arg.meta.is_llm_blocked() {
                    return Err(InterpreterError::LlmBlocked {
                        tool_name: VERIFY_HYPOTHESIS.to_string(),
                    });
                }
            }
        }

        let hypothesis = named_args
            .get("hypothesis")
            .and_then(|v| v.value.as_str())
            .unwrap_or("")
            .to_string();

        let data = named_args
            .get("data")
            .cloned()
            .unwrap_or_else(|| ValueWithMeta {
                value: serde_json::Value::Null,
                meta: Metadata::default(),
            });

        Ok(FunctionCallAction::Yield(
            ExecutionResult::NeedsVerifyHypothesis {
                hypothesis,
                data,
                call_id,
                state,
            },
        ))
    }

    /// Resumes the VM with a successful return value and its metadata.
    pub(crate) fn resume_vm_with_result(
        &mut self,
        mut state: VmSnapshot,
        result: MontyObject,
        meta: Metadata,
    ) -> Result<RunProgress<LimitedTracker>, InterpreterError> {
        // Re-inject branch checker
        let checker = PolicyBranchChecker::new(Arc::clone(&self.policy));
        state.set_branch_checker(Box::new(checker));

        let mut print_writer = CollectStringPrint::new();
        let progress = state.run(ExternalResult::return_with_meta(result, meta), &mut print_writer)?;
        self.print_output.push_str(print_writer.output());
        Ok(progress)
    }

    /// Resumes the VM with an exception (e.g., policy denial).
    pub(crate) fn resume_vm_with_exception(
        &mut self,
        mut state: VmSnapshot,
        exc: MontyException,
    ) -> Result<RunProgress<LimitedTracker>, InterpreterError> {
        // Re-inject branch checker
        let checker = PolicyBranchChecker::new(Arc::clone(&self.policy));
        state.set_branch_checker(Box::new(checker));

        let mut print_writer = CollectStringPrint::new();
        let progress = state.run(ExternalResult::Error(exc), &mut print_writer)?;
        self.print_output.push_str(print_writer.output());
        Ok(progress)
    }
}

/// Internal enum to represent the action after handling a function call.
enum FunctionCallAction {
    /// Yield this result to the caller (tool call needs external execution).
    Yield(ExecutionResult),
    /// Continue the execution loop with this new progress.
    Resume(RunProgress<LimitedTracker>),
}
